// flow-typed signature: 7421b32783d2495cd77ad0b4ca418ea4
// flow-typed version: <<STUB>>/avaron_v^0.0.12/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'avaron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'avaron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'avaron/api' {
  declare module.exports: any;
}

declare module 'avaron/cli' {
  declare module.exports: any;
}

declare module 'avaron/lib/cli' {
  declare module.exports: any;
}

declare module 'avaron/lib/fork' {
  declare module.exports: any;
}

declare module 'avaron/main/create-window' {
  declare module.exports: any;
}

declare module 'avaron/main/initialize-renderer' {
  declare module.exports: any;
}

declare module 'avaron/main/messages' {
  declare module.exports: any;
}

declare module 'avaron/main/renderer-console' {
  declare module.exports: any;
}

declare module 'avaron/main/starter' {
  declare module.exports: any;
}

declare module 'avaron/renderer/console' {
  declare module.exports: any;
}

declare module 'avaron/renderer/process-adapter' {
  declare module.exports: any;
}

declare module 'avaron/renderer/starter' {
  declare module.exports: any;
}

declare module 'avaron/renderer/test-helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'avaron/api.js' {
  declare module.exports: $Exports<'avaron/api'>;
}
declare module 'avaron/cli.js' {
  declare module.exports: $Exports<'avaron/cli'>;
}
declare module 'avaron/index' {
  declare module.exports: $Exports<'avaron'>;
}
declare module 'avaron/index.js' {
  declare module.exports: $Exports<'avaron'>;
}
declare module 'avaron/lib/cli.js' {
  declare module.exports: $Exports<'avaron/lib/cli'>;
}
declare module 'avaron/lib/fork.js' {
  declare module.exports: $Exports<'avaron/lib/fork'>;
}
declare module 'avaron/main/create-window.js' {
  declare module.exports: $Exports<'avaron/main/create-window'>;
}
declare module 'avaron/main/initialize-renderer.js' {
  declare module.exports: $Exports<'avaron/main/initialize-renderer'>;
}
declare module 'avaron/main/messages.js' {
  declare module.exports: $Exports<'avaron/main/messages'>;
}
declare module 'avaron/main/renderer-console.js' {
  declare module.exports: $Exports<'avaron/main/renderer-console'>;
}
declare module 'avaron/main/starter.js' {
  declare module.exports: $Exports<'avaron/main/starter'>;
}
declare module 'avaron/renderer/console.js' {
  declare module.exports: $Exports<'avaron/renderer/console'>;
}
declare module 'avaron/renderer/process-adapter.js' {
  declare module.exports: $Exports<'avaron/renderer/process-adapter'>;
}
declare module 'avaron/renderer/starter.js' {
  declare module.exports: $Exports<'avaron/renderer/starter'>;
}
declare module 'avaron/renderer/test-helper.js' {
  declare module.exports: $Exports<'avaron/renderer/test-helper'>;
}
