// flow-typed signature: 98af6276385f3203cdf39035c56b17f3
// flow-typed version: <<STUB>>/flow-upgrade_v^1.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-upgrade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-upgrade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-upgrade/dist/codemods/createAggregateCodemod' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/ReactUtils' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/codemods/runCodemods' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/findFlowFiles' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/index' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/Styled' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/Types' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrade' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactComponentExplicitTypeArgs/codemod' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactComponentExplicitTypeArgs/index' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactComponentSimplifyTypeArgs/codemod' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactComponentSimplifyTypeArgs/index' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactUtilityTypes/codemod' {
  declare module.exports: any;
}

declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactUtilityTypes/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-upgrade/dist/codemods/createAggregateCodemod.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/createAggregateCodemod'>;
}
declare module 'flow-upgrade/dist/codemods/ReactUtils.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/ReactUtils'>;
}
declare module 'flow-upgrade/dist/codemods/runCodemods.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/codemods/runCodemods'>;
}
declare module 'flow-upgrade/dist/findFlowFiles.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/findFlowFiles'>;
}
declare module 'flow-upgrade/dist/index.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/index'>;
}
declare module 'flow-upgrade/dist/Styled.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/Styled'>;
}
declare module 'flow-upgrade/dist/Types.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/Types'>;
}
declare module 'flow-upgrade/dist/upgrade.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrade'>;
}
declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactComponentExplicitTypeArgs/codemod.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.53.0/ReactComponentExplicitTypeArgs/codemod'>;
}
declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactComponentExplicitTypeArgs/index.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.53.0/ReactComponentExplicitTypeArgs/index'>;
}
declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactComponentSimplifyTypeArgs/codemod.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.53.0/ReactComponentSimplifyTypeArgs/codemod'>;
}
declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactComponentSimplifyTypeArgs/index.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.53.0/ReactComponentSimplifyTypeArgs/index'>;
}
declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactUtilityTypes/codemod.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.53.0/ReactUtilityTypes/codemod'>;
}
declare module 'flow-upgrade/dist/upgrades/0.53.0/ReactUtilityTypes/index.js' {
  declare module.exports: $Exports<'flow-upgrade/dist/upgrades/0.53.0/ReactUtilityTypes/index'>;
}
