// flow-typed signature: cafd33adfd903d5b688fb39991d9efbd
// flow-typed version: <<STUB>>/flow-runtime_v^0.14.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-runtime/dist/flow-runtime.es2015' {
  declare module.exports: any;
}

declare module 'flow-runtime/dist/flow-runtime' {
  declare module.exports: any;
}

declare module 'flow-runtime/dist/flow-runtime.min' {
  declare module.exports: any;
}

declare module 'flow-runtime/dist/flow-runtime.umd' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithDefaultProps' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithProps' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithTypeParameters' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/typeParametersWithInheritance' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithAnnotatedFunctionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithFunctionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithTypeParameterArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithUnionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/fixtures' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/fixtures.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/__tests__/fixtures/ParameterizedFunctionType/typeParametersWithUnionArguments' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/annotateValue' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/cache' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/classDecorators' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/cyclic' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/ClassDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/Declaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/ExtendsDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/ModuleDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/ModuleExportsDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/TypeDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/declarations/VarDeclaration' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/decorateFunction' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/decorateFunction.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/decorateGeneratorFunction' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorMessages' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/__tests__/JSONErrorReporter.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/__tests__/makeJSONError.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/__tests__/makeTypeError.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/__tests__/TypeErrorReporter.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/JSONErrorReporter' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/makeJSONError' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/makeTypeError' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/makeWarningMessage' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/RuntimeTypeError' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/errorReporting/TypeErrorReporter' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/getErrorMessage' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/globalContext' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/invariant' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/makeComparison' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/makeError' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/makeErrorMessage' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/makeReactPropTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/makeUnion' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/primitiveTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/registerBuiltins' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/registerBuiltinTypeHandlers' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/registerPrimitiveTypes' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/registerTypePredicates' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/src/registerBuiltins' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/symbols' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/typeConstraints' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/typeConstraints.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/TypeContext' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/typed.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/TypeInferrer' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/TypeInferrer.test' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/AnyType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ArrayType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/BooleanLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/BooleanType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/EmptyType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ExistentialType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FlowIntoType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FunctionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FunctionTypeParam' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FunctionTypeRestParam' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/FunctionTypeReturn' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/GeneratorType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/GenericType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/index' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/IntersectionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/MixedType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/NullableType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/NullLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/NumberType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/NumericLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ObjectType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ObjectTypeCallProperty' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ObjectTypeIndexer' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ObjectTypeProperty' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ParameterizedFunctionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/ParameterizedTypeAlias' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/PartialType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/RefinementType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/StringLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/StringType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/SymbolLiteralType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/SymbolType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TupleType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/Type' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeAlias' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeBox' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeConstructor' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeHandler' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeParameter' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeParameterApplication' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/TypeReference' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/UnionType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/types/VoidType' {
  declare module.exports: any;
}

declare module 'flow-runtime/lib/Validation' {
  declare module.exports: any;
}

declare module 'flow-runtime/test-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-runtime/dist/flow-runtime.es2015.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime.es2015'>;
}
declare module 'flow-runtime/dist/flow-runtime.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime'>;
}
declare module 'flow-runtime/dist/flow-runtime.min.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime.min'>;
}
declare module 'flow-runtime/dist/flow-runtime.umd.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime.umd'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithDefaultProps.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithDefaultProps'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithProps.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithProps'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithTypeParameters.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/simplestClassWithTypeParameters'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/typeParametersWithInheritance.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ClassDeclaration/typeParametersWithInheritance'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithAnnotatedFunctionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithAnnotatedFunctionArguments'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithFunctionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithFunctionArguments'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithTypeParameterArguments.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithTypeParameterArguments'>;
}
declare module 'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithUnionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/__fixtures__/ParameterizedFunctionType/typeParametersWithUnionArguments'>;
}
declare module 'flow-runtime/lib/__tests__/fixtures.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/fixtures'>;
}
declare module 'flow-runtime/lib/__tests__/fixtures.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/fixtures.test'>;
}
declare module 'flow-runtime/lib/__tests__/fixtures/ParameterizedFunctionType/typeParametersWithUnionArguments.js' {
  declare module.exports: $Exports<'flow-runtime/lib/__tests__/fixtures/ParameterizedFunctionType/typeParametersWithUnionArguments'>;
}
declare module 'flow-runtime/lib/annotateValue.js' {
  declare module.exports: $Exports<'flow-runtime/lib/annotateValue'>;
}
declare module 'flow-runtime/lib/cache.js' {
  declare module.exports: $Exports<'flow-runtime/lib/cache'>;
}
declare module 'flow-runtime/lib/classDecorators.js' {
  declare module.exports: $Exports<'flow-runtime/lib/classDecorators'>;
}
declare module 'flow-runtime/lib/cyclic.js' {
  declare module.exports: $Exports<'flow-runtime/lib/cyclic'>;
}
declare module 'flow-runtime/lib/declarations/ClassDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/ClassDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/Declaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/Declaration'>;
}
declare module 'flow-runtime/lib/declarations/ExtendsDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/ExtendsDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/index.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/index'>;
}
declare module 'flow-runtime/lib/declarations/ModuleDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/ModuleDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/ModuleExportsDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/ModuleExportsDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/TypeDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/TypeDeclaration'>;
}
declare module 'flow-runtime/lib/declarations/VarDeclaration.js' {
  declare module.exports: $Exports<'flow-runtime/lib/declarations/VarDeclaration'>;
}
declare module 'flow-runtime/lib/decorateFunction.js' {
  declare module.exports: $Exports<'flow-runtime/lib/decorateFunction'>;
}
declare module 'flow-runtime/lib/decorateFunction.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/decorateFunction.test'>;
}
declare module 'flow-runtime/lib/decorateGeneratorFunction.js' {
  declare module.exports: $Exports<'flow-runtime/lib/decorateGeneratorFunction'>;
}
declare module 'flow-runtime/lib/errorMessages.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorMessages'>;
}
declare module 'flow-runtime/lib/errorReporting/__tests__/JSONErrorReporter.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/__tests__/JSONErrorReporter.test'>;
}
declare module 'flow-runtime/lib/errorReporting/__tests__/makeJSONError.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/__tests__/makeJSONError.test'>;
}
declare module 'flow-runtime/lib/errorReporting/__tests__/makeTypeError.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/__tests__/makeTypeError.test'>;
}
declare module 'flow-runtime/lib/errorReporting/__tests__/TypeErrorReporter.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/__tests__/TypeErrorReporter.test'>;
}
declare module 'flow-runtime/lib/errorReporting/JSONErrorReporter.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/JSONErrorReporter'>;
}
declare module 'flow-runtime/lib/errorReporting/makeJSONError.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/makeJSONError'>;
}
declare module 'flow-runtime/lib/errorReporting/makeTypeError.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/makeTypeError'>;
}
declare module 'flow-runtime/lib/errorReporting/makeWarningMessage.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/makeWarningMessage'>;
}
declare module 'flow-runtime/lib/errorReporting/RuntimeTypeError.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/RuntimeTypeError'>;
}
declare module 'flow-runtime/lib/errorReporting/TypeErrorReporter.js' {
  declare module.exports: $Exports<'flow-runtime/lib/errorReporting/TypeErrorReporter'>;
}
declare module 'flow-runtime/lib/getErrorMessage.js' {
  declare module.exports: $Exports<'flow-runtime/lib/getErrorMessage'>;
}
declare module 'flow-runtime/lib/globalContext.js' {
  declare module.exports: $Exports<'flow-runtime/lib/globalContext'>;
}
declare module 'flow-runtime/lib/index.cjs.js' {
  declare module.exports: $Exports<'flow-runtime/lib/index.cjs'>;
}
declare module 'flow-runtime/lib/index.js' {
  declare module.exports: $Exports<'flow-runtime/lib/index'>;
}
declare module 'flow-runtime/lib/invariant.js' {
  declare module.exports: $Exports<'flow-runtime/lib/invariant'>;
}
declare module 'flow-runtime/lib/makeComparison.js' {
  declare module.exports: $Exports<'flow-runtime/lib/makeComparison'>;
}
declare module 'flow-runtime/lib/makeError.js' {
  declare module.exports: $Exports<'flow-runtime/lib/makeError'>;
}
declare module 'flow-runtime/lib/makeErrorMessage.js' {
  declare module.exports: $Exports<'flow-runtime/lib/makeErrorMessage'>;
}
declare module 'flow-runtime/lib/makeReactPropTypes.js' {
  declare module.exports: $Exports<'flow-runtime/lib/makeReactPropTypes'>;
}
declare module 'flow-runtime/lib/makeUnion.js' {
  declare module.exports: $Exports<'flow-runtime/lib/makeUnion'>;
}
declare module 'flow-runtime/lib/primitiveTypes.js' {
  declare module.exports: $Exports<'flow-runtime/lib/primitiveTypes'>;
}
declare module 'flow-runtime/lib/registerBuiltins.js' {
  declare module.exports: $Exports<'flow-runtime/lib/registerBuiltins'>;
}
declare module 'flow-runtime/lib/registerBuiltinTypeHandlers.js' {
  declare module.exports: $Exports<'flow-runtime/lib/registerBuiltinTypeHandlers'>;
}
declare module 'flow-runtime/lib/registerPrimitiveTypes.js' {
  declare module.exports: $Exports<'flow-runtime/lib/registerPrimitiveTypes'>;
}
declare module 'flow-runtime/lib/registerTypePredicates.js' {
  declare module.exports: $Exports<'flow-runtime/lib/registerTypePredicates'>;
}
declare module 'flow-runtime/lib/src/registerBuiltins.js' {
  declare module.exports: $Exports<'flow-runtime/lib/src/registerBuiltins'>;
}
declare module 'flow-runtime/lib/symbols.js' {
  declare module.exports: $Exports<'flow-runtime/lib/symbols'>;
}
declare module 'flow-runtime/lib/typeConstraints.js' {
  declare module.exports: $Exports<'flow-runtime/lib/typeConstraints'>;
}
declare module 'flow-runtime/lib/typeConstraints.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/typeConstraints.test'>;
}
declare module 'flow-runtime/lib/TypeContext.js' {
  declare module.exports: $Exports<'flow-runtime/lib/TypeContext'>;
}
declare module 'flow-runtime/lib/typed.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/typed.test'>;
}
declare module 'flow-runtime/lib/TypeInferrer.js' {
  declare module.exports: $Exports<'flow-runtime/lib/TypeInferrer'>;
}
declare module 'flow-runtime/lib/TypeInferrer.test.js' {
  declare module.exports: $Exports<'flow-runtime/lib/TypeInferrer.test'>;
}
declare module 'flow-runtime/lib/types/AnyType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/AnyType'>;
}
declare module 'flow-runtime/lib/types/ArrayType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ArrayType'>;
}
declare module 'flow-runtime/lib/types/BooleanLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/BooleanLiteralType'>;
}
declare module 'flow-runtime/lib/types/BooleanType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/BooleanType'>;
}
declare module 'flow-runtime/lib/types/EmptyType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/EmptyType'>;
}
declare module 'flow-runtime/lib/types/ExistentialType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ExistentialType'>;
}
declare module 'flow-runtime/lib/types/FlowIntoType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FlowIntoType'>;
}
declare module 'flow-runtime/lib/types/FunctionType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FunctionType'>;
}
declare module 'flow-runtime/lib/types/FunctionTypeParam.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FunctionTypeParam'>;
}
declare module 'flow-runtime/lib/types/FunctionTypeRestParam.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FunctionTypeRestParam'>;
}
declare module 'flow-runtime/lib/types/FunctionTypeReturn.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/FunctionTypeReturn'>;
}
declare module 'flow-runtime/lib/types/GeneratorType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/GeneratorType'>;
}
declare module 'flow-runtime/lib/types/GenericType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/GenericType'>;
}
declare module 'flow-runtime/lib/types/index.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/index'>;
}
declare module 'flow-runtime/lib/types/IntersectionType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/IntersectionType'>;
}
declare module 'flow-runtime/lib/types/MixedType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/MixedType'>;
}
declare module 'flow-runtime/lib/types/NullableType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/NullableType'>;
}
declare module 'flow-runtime/lib/types/NullLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/NullLiteralType'>;
}
declare module 'flow-runtime/lib/types/NumberType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/NumberType'>;
}
declare module 'flow-runtime/lib/types/NumericLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/NumericLiteralType'>;
}
declare module 'flow-runtime/lib/types/ObjectType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ObjectType'>;
}
declare module 'flow-runtime/lib/types/ObjectTypeCallProperty.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ObjectTypeCallProperty'>;
}
declare module 'flow-runtime/lib/types/ObjectTypeIndexer.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ObjectTypeIndexer'>;
}
declare module 'flow-runtime/lib/types/ObjectTypeProperty.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ObjectTypeProperty'>;
}
declare module 'flow-runtime/lib/types/ParameterizedFunctionType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ParameterizedFunctionType'>;
}
declare module 'flow-runtime/lib/types/ParameterizedTypeAlias.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/ParameterizedTypeAlias'>;
}
declare module 'flow-runtime/lib/types/PartialType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/PartialType'>;
}
declare module 'flow-runtime/lib/types/RefinementType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/RefinementType'>;
}
declare module 'flow-runtime/lib/types/StringLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/StringLiteralType'>;
}
declare module 'flow-runtime/lib/types/StringType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/StringType'>;
}
declare module 'flow-runtime/lib/types/SymbolLiteralType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/SymbolLiteralType'>;
}
declare module 'flow-runtime/lib/types/SymbolType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/SymbolType'>;
}
declare module 'flow-runtime/lib/types/TupleType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TupleType'>;
}
declare module 'flow-runtime/lib/types/Type.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/Type'>;
}
declare module 'flow-runtime/lib/types/TypeAlias.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeAlias'>;
}
declare module 'flow-runtime/lib/types/TypeBox.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeBox'>;
}
declare module 'flow-runtime/lib/types/TypeConstructor.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeConstructor'>;
}
declare module 'flow-runtime/lib/types/TypeHandler.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeHandler'>;
}
declare module 'flow-runtime/lib/types/TypeParameter.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeParameter'>;
}
declare module 'flow-runtime/lib/types/TypeParameterApplication.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeParameterApplication'>;
}
declare module 'flow-runtime/lib/types/TypeReference.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/TypeReference'>;
}
declare module 'flow-runtime/lib/types/UnionType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/UnionType'>;
}
declare module 'flow-runtime/lib/types/VoidType.js' {
  declare module.exports: $Exports<'flow-runtime/lib/types/VoidType'>;
}
declare module 'flow-runtime/lib/Validation.js' {
  declare module.exports: $Exports<'flow-runtime/lib/Validation'>;
}
declare module 'flow-runtime/test-polyfill.js' {
  declare module.exports: $Exports<'flow-runtime/test-polyfill'>;
}
