// flow-typed signature: 2b5cedcf0be848e319f57958171a24e2
// flow-typed version: <<STUB>>/karma-nightmare_v^0.4.10/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-nightmare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-nightmare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-nightmare/client/index' {
  declare module.exports: any;
}

declare module 'karma-nightmare/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-nightmare/lib/browser' {
  declare module.exports: any;
}

declare module 'karma-nightmare/lib/custom-script' {
  declare module.exports: any;
}

declare module 'karma-nightmare/test/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-nightmare/client/index.js' {
  declare module.exports: $Exports<'karma-nightmare/client/index'>;
}
declare module 'karma-nightmare/index' {
  declare module.exports: $Exports<'karma-nightmare'>;
}
declare module 'karma-nightmare/index.js' {
  declare module.exports: $Exports<'karma-nightmare'>;
}
declare module 'karma-nightmare/karma.conf.js' {
  declare module.exports: $Exports<'karma-nightmare/karma.conf'>;
}
declare module 'karma-nightmare/lib/browser.js' {
  declare module.exports: $Exports<'karma-nightmare/lib/browser'>;
}
declare module 'karma-nightmare/lib/custom-script.js' {
  declare module.exports: $Exports<'karma-nightmare/lib/custom-script'>;
}
declare module 'karma-nightmare/test/index.spec.js' {
  declare module.exports: $Exports<'karma-nightmare/test/index.spec'>;
}
