// flow-typed signature: 82ca72919c1bcbe27fd5dd3f9602ca6e
// flow-typed version: <<STUB>>/power-assert_v^1.4.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'power-assert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'power-assert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'power-assert/build/power-assert' {
  declare module.exports: any;
}

// Filename aliases
declare module 'power-assert/build/power-assert.js' {
  declare module.exports: $Exports<'power-assert/build/power-assert'>;
}
declare module 'power-assert/index' {
  declare module.exports: $Exports<'power-assert'>;
}
declare module 'power-assert/index.js' {
  declare module.exports: $Exports<'power-assert'>;
}
