// flow-typed signature: 2e2fdcbb011c91f1fd2b29ad382ffc17
// flow-typed version: <<STUB>>/react-resizable-box_vnext/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-resizable-box'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-resizable-box' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-resizable-box/lib/index' {
  declare module.exports: any;
}

declare module 'react-resizable-box/lib/react-resizable-box' {
  declare module.exports: any;
}

declare module 'react-resizable-box/lib/resizer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-resizable-box/lib/index.js' {
  declare module.exports: $Exports<'react-resizable-box/lib/index'>;
}
declare module 'react-resizable-box/lib/react-resizable-box.js' {
  declare module.exports: $Exports<'react-resizable-box/lib/react-resizable-box'>;
}
declare module 'react-resizable-box/lib/resizer.js' {
  declare module.exports: $Exports<'react-resizable-box/lib/resizer'>;
}
