// flow-typed signature: d5b5d5461b17b77a8dc8228fed3f5d1a
// flow-typed version: <<STUB>>/rollup-plugin-node-globals_v1.1.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-node-globals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-node-globals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-node-globals/dist/rollup-plugin-node-globals.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-globals/dist/rollup-plugin-node-globals.es6' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-globals/src/browser' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-globals/src/global' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-globals/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-globals/src/inject/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-globals/src/inject/makeLegalIdentifier' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-node-globals/dist/rollup-plugin-node-globals.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-node-globals/dist/rollup-plugin-node-globals.cjs'>;
}
declare module 'rollup-plugin-node-globals/dist/rollup-plugin-node-globals.es6.js' {
  declare module.exports: $Exports<'rollup-plugin-node-globals/dist/rollup-plugin-node-globals.es6'>;
}
declare module 'rollup-plugin-node-globals/src/browser.js' {
  declare module.exports: $Exports<'rollup-plugin-node-globals/src/browser'>;
}
declare module 'rollup-plugin-node-globals/src/global.js' {
  declare module.exports: $Exports<'rollup-plugin-node-globals/src/global'>;
}
declare module 'rollup-plugin-node-globals/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-node-globals/src/index'>;
}
declare module 'rollup-plugin-node-globals/src/inject/index.js' {
  declare module.exports: $Exports<'rollup-plugin-node-globals/src/inject/index'>;
}
declare module 'rollup-plugin-node-globals/src/inject/makeLegalIdentifier.js' {
  declare module.exports: $Exports<'rollup-plugin-node-globals/src/inject/makeLegalIdentifier'>;
}
