// flow-typed signature: 94c7e3123b2449cc5c2ea90893e611f9
// flow-typed version: <<STUB>>/webpack-async-await_v^1.1.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-async-await'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-async-await' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-async-await/plugin' {
  declare module.exports: any;
}

declare module 'webpack-async-await/test/index' {
  declare module.exports: any;
}

declare module 'webpack-async-await/test/test-input' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-async-await/plugin.js' {
  declare module.exports: $Exports<'webpack-async-await/plugin'>;
}
declare module 'webpack-async-await/test/index.js' {
  declare module.exports: $Exports<'webpack-async-await/test/index'>;
}
declare module 'webpack-async-await/test/test-input.js' {
  declare module.exports: $Exports<'webpack-async-await/test/test-input'>;
}
