// flow-typed signature: 66dd44db17390b8a6767c96667f14fc4
// flow-typed version: <<STUB>>/@storybook/addon-actions_v^3.2.6/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-actions/dist/components/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/containers/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/components/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/containers/ActionLogger/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/preview.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-actions/dist/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/components/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/dist/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/components/ActionLogger/style'>;
}
declare module '@storybook/addon-actions/dist/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/containers/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/index'>;
}
declare module '@storybook/addon-actions/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/manager'>;
}
declare module '@storybook/addon-actions/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview'>;
}
declare module '@storybook/addon-actions/register.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/register'>;
}
declare module '@storybook/addon-actions/src/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/components/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/src/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/components/ActionLogger/style'>;
}
declare module '@storybook/addon-actions/src/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/containers/ActionLogger/index'>;
}
declare module '@storybook/addon-actions/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/index'>;
}
declare module '@storybook/addon-actions/src/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/manager'>;
}
declare module '@storybook/addon-actions/src/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview'>;
}
declare module '@storybook/addon-actions/src/preview.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/preview.test'>;
}
