// flow-typed signature: 15f82cf3cf4b7257db7f1ed425f25257
// flow-typed version: <<STUB>>/@storybook/addon-links_v^3.2.6/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-links/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/preview' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-links/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/index'>;
}
declare module '@storybook/addon-links/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/manager'>;
}
declare module '@storybook/addon-links/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/preview'>;
}
declare module '@storybook/addon-links/register.js' {
  declare module.exports: $Exports<'@storybook/addon-links/register'>;
}
declare module '@storybook/addon-links/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/src/index'>;
}
declare module '@storybook/addon-links/src/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-links/src/manager'>;
}
declare module '@storybook/addon-links/src/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/src/preview'>;
}
